os:
- linux
language: node_js
node_js:
- '8'
sudo: required
dist: trusty
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CHROME_BIN=/usr/bin/google-chrome;
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
- npm install --cache-min 999999999
- npm i -g npm
install:
- npm install
before_script:
- npm run build
notifications:
  slack:
    secure: PUPMZ2+nU9DJ0IExfVdjXK2QuYuB6AcVIWsWc/JGKkPyhJo1fWdKF7yrBURwD2bj++99yPcnbtWtzju2w0hKm2pcx/08hcGVmsitOfdPYNc/tN8nJUAFJutqAibxLDmYh0OXlU0N6AiFAbka/ePrEa7tCEtUrF5PRcEHdJuClCTqR+URWZCp65fGpY+bMCrw5EXETxNQce4OLzEcQXi9B4CYqv/VNcXlHHaLYjojgHNCdL927AJJkQww41Myo5vqAaycwARS1+LRCzEOHGauxMJvMxDME5VykSRdVsU3vKx/070XU+QmDfVaFiBJBixFzEwwcGh7r6SwSdJRf3CNgtfm7sYUsRl28DBBhjZ5uHMZZfiGllfEdNZDW1safxZpk1Sr5oC5EKEwqcdSiqoNJgdVqf9vdliBcVu9TzhZUexyNKsi5Kaer90aWNcLksTbzvf2h3cgdAUXqSMOboRgRFlgtHc0zxz/AN4CXm3feGVLX3q+6jXXPqlXD2laBzdMquSJOXPvA7tr9qn7XZrSAEMtTUGVHzu77B1u0tAfc7SOvVRVa/YWe3QxWDQVEQvsqrxtyon/NfP5xVLkcbxrVZN6rJtyTRR9+11ZviMLE5WEcqKkyjubrekrR8CdHU8ZplqsyvQZN1YhBS/by+am758u1Zd/TZf1TsGcmFIWUpg=
    on_success: change
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: 'docs/.vuepress/dist'
  on:
    branch: master
env:
  matrix:
    secure: XpIhtHueJaw8JUnn7mQn0cYL6aUsvcq6ca1I6KxKI1Wrlc4VEq86FM8fxP2qniYDiCYHldKW85RBO44UhJ6VFD6JS3+fPT1nPyqTX8tKP86wVqljxWKuDcEdUNwAUE+IiAyBfR1lazfoON5PSPrZs3TmBjs8y4lkUteVXHahYVhjrNzfs72C+4nopRzLCWIU+Xa24/wEEOwm/6aj2uskajhknEZICd0j7vHw14Nm7IzDwcZYvyPl5JXP4a/5bLyQVVTBKh3Q8dI7pUQDT7pczh3wycbXkgOFVu3r59+E5wZkKShZ7tHl36GIliAU0tnbA31KFjv9YFA62435zVJNdHMCLkyUZouXDxzkQSp1zj0no6MCaaPWLsXSeZMZWaG5KZhMaa7qOxizhsTuHzSSTY12YJyJWvCUG5nf1SSNftB2MkOyfqiDL/rJBHAXKzi97jfytlExpYoojp98Tu0CqeW3R3dyvug7LKBbkjP1L3aMy33mHsnMNfGibj3M7wbXW4Glrm0Dnlz71XYsFe1CbGgkUWv0RdEU6blLwqVJO0IlWnDazKwVbGWLqA8swhWHnq/WHZNNUEfEIDp0j8aUdL6m0GKoKpcuAozBA60pR/lzX+dYLXfIajVu1YHc0TIC5XyU9veQ+/AHDboyR9smSk+woGxyNl7NUIKwSGgWUUQ=
